stages:
  - test

test:2.7:
  image: python:2.7
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests -p "test_*.py"
    - python setup.py install
test:3.4:
  image: python:3.4
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests -p "test_*.py"
    - python setup.py install
# test:3.5:
#   image: python 3.5
#   stage: test
#   script:
#     - pip install -r requirements.txt
#     - python -m unittest discover -s tests -p "test_*.py"
#     - python setup.py install
test:3.6:
  image: python:3.6
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests -p "test_*.py"
    - python setup.py install
