language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest discover -s tests -p "test_*.py"
- python setup.py install
- openapi-cli-tool list ./tests/resources/spec
- openapi-cli-tool bundle -t yaml ./tests/resources/spec/folder1
deploy:
  provider: pypi
  user: hakopako
  password:
    secure: HVOWyH+/75hwhdVYl9fUdIp0nHEERrYWg2aGs02hT8qONDCvQcfvUDG54eg3jL4wq+1knPU5Pvb4vpht3nbibmZDJLz4B/fukZ+9H8CFKAvWKaOa2lEtPKLKTqdTlupRPSkyQIo4dtyemKI6r5ganFaNFc3T2UOY3IIfW8XfUzqldn9MzzQ9jJlqCrsnF24ArSlxkC0UofUkYclyA5U4GLPDJ01Rj6E2HPVrb6iajBiqL6+5beZAybumnIwlc32lFx5T8epy2bVl3qeFc2mJ8bEpD4CwO2BXn+UHvUEI7yz9DPi5fFK/QznLZShdpgY4JcT9E7YNXV+R/yaA2Mpma5HlB3GTCUFg9UuB6WHgM4Z9baGnnH0Ft10nxup3wGiKMtctsOOPjL5+aGqtrQJ63QIx+nfqY62iAtn6PTbYEZd3iZGSXiS0jcJaArAQ2ePNskl/59lv/EUDMSWOkg35Y9ZWJZJMZKW6WQcBwmAPUN6nUrHUgaacDrsIxnuMaHxQMF51oWvc+Znmxc3bRiAW+woScpncSgYfxbaeRKlzYFj0IBrFg0TVAcHmKYT1ib1ChmKXqrDpw2E1KUJvL0WDQ4fQ2iwZwejPS7zNUmnf6iKvU0LT2go+ct6T5gsakfT4CFCL6EJGRV1jJSCLIkgxTRvw56GsTmBbdSaLEsh9mBc=
  server: https://pypi.org/project/openapi-cli-tool
  on:
    tags: true
